default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: chessfork2_development

test:
  <<: *default
  database: chessfork2_test

production:
  <<: *default
  database: chessfork2_production
