default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: postgres
  password:


development:
  <<: *default
  database: chessfork2_development

test:
  <<: *default
  database: chessfork2_test

production:
  <<: *default
  database: chessfork2_production
